import { mkdir, readFile, readdir, stat, writeFile } from 'node:fs/promises'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

import {
  validateQuestionManifest,
  type GeneratedLocalQuestionBundle,
  type PlayableQuestionManifest,
  type QuestionManifest,
} from '../src/data/question-manifest.ts'
import {
  createQuestionDirectoryName,
  parseQuestionDirectoryName,
} from '../src/data/question-directory.ts'
import { createGeneratedLocalQuestionBundle } from '../src/data/question-client.ts'
import { materializePlayableQuestionManifest } from '../src/data/playable-question.ts'
import type { InternationalCatalog } from '../src/data/catalog/types.ts'
import { validateInternationalCatalog } from '../src/data/catalog/validation.ts'

const scriptDirectory = dirname(fileURLToPath(import.meta.url))
const repositoryRoot = resolve(scriptDirectory, '..')
const sourceRoot = resolve(repositoryRoot, 'sources/questions')
const catalogPath = resolve(repositoryRoot, 'src/data/catalog/international-catalog.json')
const generatedPath = resolve(repositoryRoot, 'src/data/questions.generated.ts')

interface LoadedQuestionManifest {
  id: string
  playableManifest: PlayableQuestionManifest | null
}

function isMissingFileError(error: unknown): boolean {
  return error instanceof Error && (error as NodeJS.ErrnoException).code === 'ENOENT'
}

async function fileExists(path: string): Promise<boolean> {
  try {
    return (await stat(path)).isFile()
  } catch (error) {
    if (isMissingFileError(error)) {
      return false
    }

    throw new Error(
      `Unable to inspect ${path}: ${error instanceof Error ? error.message : String(error)}`,
      { cause: error },
    )
  }
}

async function readTextIfExists(path: string): Promise<string | null> {
  try {
    return await readFile(path, 'utf8')
  } catch (error) {
    if (isMissingFileError(error)) {
      return null
    }

    throw new Error(
      `Unable to read ${path}: ${error instanceof Error ? error.message : String(error)}`,
      { cause: error },
    )
  }
}

async function readJson(path: string): Promise<unknown> {
  return JSON.parse(await readFile(path, 'utf8')) as unknown
}

function createGeneratedModule(bundles: readonly GeneratedLocalQuestionBundle[]): string {
  const serialized = JSON.stringify(bundles, null, 2)

  return `// Generated by scripts/sync-question-catalog.ts. Do not edit directly.\n\nimport type { GeneratedLocalQuestionBundle } from './question-manifest'\n\nexport const playableQuestionBundles = ${serialized} as const satisfies readonly GeneratedLocalQuestionBundle[]\n`
}

async function loadCatalog(): Promise<InternationalCatalog> {
  const value = await readJson(catalogPath)
  const catalog = value as InternationalCatalog
  const issues = validateInternationalCatalog(catalog)

  if (issues.length > 0) {
    throw new Error(`International catalog is invalid:\n- ${issues.join('\n- ')}`)
  }

  return catalog
}

async function loadQuestionManifests(
  catalog: InternationalCatalog,
): Promise<readonly LoadedQuestionManifest[]> {
  const entries = (await readdir(sourceRoot, { withFileTypes: true }))
    .filter((entry) => entry.isDirectory())
    .sort((left, right) => left.name.localeCompare(right.name))
  const manifests: LoadedQuestionManifest[] = []
  const issues: string[] = []
  const directoryById = new Map<string, string>()

  for (const entry of entries) {
    const manifestPath = resolve(sourceRoot, entry.name, 'question.json')
    const originalPath = resolve(sourceRoot, entry.name, 'original.png')
    const redactedPath = resolve(sourceRoot, entry.name, 'redacted.webp')
    const parsedDirectory = parseQuestionDirectoryName(entry.name)

    if (parsedDirectory === null) {
      issues.push(
        `${entry.name}: directory name must be <event>--<stage>--<blue>--<red>--g<game>--<12-character-id>`,
      )
    }

    if (!(await fileExists(manifestPath))) {
      issues.push(`${entry.name}: missing question.json`)
      continue
    }

    let value: unknown

    try {
      value = await readJson(manifestPath)
    } catch (error) {
      issues.push(
        `${entry.name}: question.json is not valid JSON: ${error instanceof Error ? error.message : String(error)}`,
      )
      continue
    }

    const manifestIssues = validateQuestionManifest(value, {
      catalog,
    })

    issues.push(...manifestIssues.map((issue) => `${entry.name}: ${issue}`))

    if (manifestIssues.length > 0) {
      continue
    }

    if (parsedDirectory === null) {
      continue
    }

    const existingDirectory = directoryById.get(parsedDirectory.id)

    if (existingDirectory !== undefined) {
      issues.push(
        `${entry.name}: question ID ${parsedDirectory.id} is already used by ${existingDirectory}`,
      )
    } else {
      directoryById.set(parsedDirectory.id, entry.name)
    }

    const expectedDirectory = createQuestionDirectoryName(
      parsedDirectory.id,
      value as QuestionManifest,
    )

    if (entry.name !== expectedDirectory) {
      issues.push(
        `${entry.name}: directory name does not match question.json; expected ${expectedDirectory}`,
      )
    }

    if (!(await fileExists(originalPath))) {
      issues.push(`${entry.name}: question is missing original.png`)
    }

    let playableManifest: PlayableQuestionManifest | null = null

    if (await fileExists(redactedPath)) {
      try {
        playableManifest = materializePlayableQuestionManifest(
          parsedDirectory.id,
          value as QuestionManifest,
          catalog,
        )
      } catch (error) {
        issues.push(error instanceof Error ? error.message : String(error))
        continue
      }

      const playableIssues = validateQuestionManifest(playableManifest, {
        catalog,
        ready: true,
      })

      issues.push(...playableIssues.map((issue) => `${entry.name}: ${issue}`))
    }

    manifests.push({ id: parsedDirectory.id, playableManifest })
  }

  if (issues.length > 0) {
    throw new Error(`Question manifests are invalid:\n- ${issues.join('\n- ')}`)
  }

  return manifests
}

async function main(): Promise<void> {
  const arguments_ = new Set(process.argv.slice(2))
  const checkOnly = arguments_.delete('--check')

  if (arguments_.size > 0) {
    throw new Error(`Unknown arguments: ${[...arguments_].join(', ')}`)
  }

  const catalog = await loadCatalog()
  const manifests = await loadQuestionManifests(catalog)
  const playable = manifests
    .filter(
      (record): record is LoadedQuestionManifest & { playableManifest: PlayableQuestionManifest } =>
        record.playableManifest !== null,
    )
    .sort((left, right) => left.id.localeCompare(right.id))

  const generatedModule = createGeneratedModule(
    playable.map(({ id, playableManifest }) =>
      createGeneratedLocalQuestionBundle(id, playableManifest, catalog),
    ),
  )

  if (checkOnly) {
    const existingModule = await readTextIfExists(generatedPath)

    if (existingModule !== generatedModule) {
      throw new Error('Question catalog is stale; run npm run questions:sync')
    }

    console.error(
      `Verified ${manifests.length} question manifests and ${playable.length} playable questions`,
    )
    return
  }

  await mkdir(dirname(generatedPath), { recursive: true })
  await writeFile(generatedPath, generatedModule, 'utf8')
  console.error(`Generated ${playable.length} playable questions from ${manifests.length} manifests`)
}

await main()
