import { mkdir, readFile, readdir, stat, writeFile } from 'node:fs/promises'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

import {
  getQuestionPublicImageFilename,
  QUESTION_ID_PATTERN,
  validatePublicQuestionImageInventory,
  validateQuestionManifest,
  type GeneratedLocalQuestionBundle,
  type PublishedQuestionManifest,
  type QuestionManifest,
} from '../src/data/question-manifest.ts'
import { createGeneratedLocalQuestionBundle } from '../src/data/question-client.ts'
import type { InternationalCatalog } from '../src/data/catalog/types.ts'
import { validateInternationalCatalog } from '../src/data/catalog/validation.ts'

const scriptDirectory = dirname(fileURLToPath(import.meta.url))
const repositoryRoot = resolve(scriptDirectory, '..')
const sourceRoot = resolve(repositoryRoot, 'sources/questions')
const publicRoot = resolve(repositoryRoot, 'public/questions')
const catalogPath = resolve(repositoryRoot, 'src/data/catalog/international-catalog.json')
const generatedPath = resolve(repositoryRoot, 'src/data/questions.generated.ts')

interface LoadedQuestionManifest {
  id: string
  manifest: QuestionManifest
  published: boolean
}

async function fileExists(path: string): Promise<boolean> {
  try {
    return (await stat(path)).isFile()
  } catch {
    return false
  }
}

async function readJson(path: string): Promise<unknown> {
  return JSON.parse(await readFile(path, 'utf8')) as unknown
}

function createGeneratedModule(bundles: readonly GeneratedLocalQuestionBundle[]): string {
  const serialized = JSON.stringify(bundles, null, 2)

  return `// Generated by scripts/sync-question-catalog.ts. Do not edit directly.\n\nimport type { GeneratedLocalQuestionBundle } from './question-manifest'\n\nexport const publishedQuestionBundles = ${serialized} as const satisfies readonly GeneratedLocalQuestionBundle[]\n`
}

async function loadCatalog(): Promise<InternationalCatalog> {
  const value = await readJson(catalogPath)
  const catalog = value as InternationalCatalog
  const issues = validateInternationalCatalog(catalog)

  if (issues.length > 0) {
    throw new Error(`International catalog is invalid:\n- ${issues.join('\n- ')}`)
  }

  return catalog
}

async function loadQuestionManifests(
  catalog: InternationalCatalog,
  publicImageFilenames: readonly string[],
): Promise<readonly LoadedQuestionManifest[]> {
  const entries = (await readdir(sourceRoot, { withFileTypes: true }))
    .filter((entry) => entry.isDirectory())
    .sort((left, right) => left.name.localeCompare(right.name))
  const manifests: LoadedQuestionManifest[] = []
  const issues: string[] = []
  const questionIds = new Set(entries.map((entry) => entry.name))
  const publicImages = new Set(publicImageFilenames)

  issues.push(...validatePublicQuestionImageInventory(publicImageFilenames, questionIds))

  for (const entry of entries) {
    const manifestPath = resolve(sourceRoot, entry.name, 'question.json')
    const published = publicImages.has(getQuestionPublicImageFilename(entry.name))

    if (!QUESTION_ID_PATTERN.test(entry.name)) {
      issues.push(`${entry.name}: directory name is not an opaque question ID`)
    }

    if (!(await fileExists(manifestPath))) {
      issues.push(`${entry.name}: missing question.json`)
      continue
    }

    let value: unknown

    try {
      value = await readJson(manifestPath)
    } catch (error) {
      issues.push(
        `${entry.name}: question.json is not valid JSON: ${error instanceof Error ? error.message : String(error)}`,
      )
      continue
    }

    const manifestIssues = validateQuestionManifest(value, {
      catalog,
      published,
    })

    issues.push(...manifestIssues.map((issue) => `${entry.name}: ${issue}`))

    if (manifestIssues.length > 0) {
      continue
    }

    const manifest = value as QuestionManifest

    if (!(await fileExists(resolve(sourceRoot, entry.name, 'original.png')))) {
      issues.push(`${entry.name}: question is missing original.png`)
    }

    manifests.push({ id: entry.name, manifest, published })
  }

  if (issues.length > 0) {
    throw new Error(`Question manifests are invalid:\n- ${issues.join('\n- ')}`)
  }

  return manifests
}

async function main(): Promise<void> {
  const arguments_ = new Set(process.argv.slice(2))
  const checkOnly = arguments_.delete('--check')

  if (arguments_.size > 0) {
    throw new Error(`Unknown arguments: ${[...arguments_].join(', ')}`)
  }

  const catalog = await loadCatalog()
  const publicImageFilenames = (await readdir(publicRoot, { withFileTypes: true }))
    .filter((entry) => entry.isFile())
    .map((entry) => entry.name)
  const manifests = await loadQuestionManifests(catalog, publicImageFilenames)
  const published = manifests
    .filter((record) => record.published)
    .map((record) => ({
      id: record.id,
      manifest: record.manifest as PublishedQuestionManifest,
    }))
    .sort((left, right) => left.id.localeCompare(right.id))

  const generatedModule = createGeneratedModule(
    published.map(({ id, manifest }) =>
      createGeneratedLocalQuestionBundle(id, manifest, catalog),
    ),
  )

  if (checkOnly) {
    const existingModule = await readFile(generatedPath, 'utf8').catch(() => '')

    if (existingModule !== generatedModule) {
      throw new Error('Question catalog is stale; run npm run questions:sync')
    }

    console.error(`Verified ${manifests.length} question manifests and ${published.length} published question`)
    return
  }

  await mkdir(dirname(generatedPath), { recursive: true })
  await writeFile(generatedPath, generatedModule, 'utf8')
  console.error(`Generated ${published.length} published question from ${manifests.length} manifests`)
}

await main()
