// Generated by scripts/sync-question-catalog.ts. Do not edit directly.

import type { GeneratedLocalQuestionBundle } from './question-manifest'

export const publishedQuestionBundles = [] as const satisfies readonly GeneratedLocalQuestionBundle[]
