// Generated by scripts/sync-question-catalog.ts. Do not edit directly.

import type { PublishedQuestionManifest } from './question-manifest'

export const publishedQuestionManifests = [] as const satisfies readonly PublishedQuestionManifest[]
